<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>predictive risk</name>
  <uuid>4631738d-a1fd-429d-b51f-7dc510cba963</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the machine learning scoreboard computed from ClientInformation being Client , Industry being Industry ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
